### ISSUE TITLE
Import MisalignTransform fails with current version

### ISSUE THREAD

**Issue by ndebs** [MIC-DKFZ/misalignment_DA#1]
Hi,

I followed the instructions for installing misalignement depedencies with:
```
https://github.com/MIC-DKFZ/misalignment_DA.git
cd misalignment-DA
pip install -e .
```
but it failed when I launch nnUNet with nnUNetTrainer_Misalign trainer:
`nnUNetv2_train 001 3d_fullres 0 -tr nnUNetTrainer_Misalign --npz`

MisalignTransform could not be imported from /batchgenerators/transforms/spatial_transforms.py. Actually, spatial_transforms.py was exactly the same as the one on nnUNet_v2 master branch, and did not contain 'MisalignTransform' class. 

I tried then to force the installation of batchgenerators with a recent version (v 0.23.2 should contain Misalignment data augmentation), but it didn't worked either. 

Best regards,

Noëlie

**Comment by Kobalt93** [comment]
Hi Noëlie,
strange, I will doublecheck it, could you please try this command?: `pip install --upgrade --force-reinstall git+https://github.com/MIC-DKFZ/batchgenerators.git`
Let me know it it doesnt work.

**Comment by ndebs** [comment]
Hi,
Thanks for your answer! by forcing batchgenerator install it worked !

**Comment by Kobalt93** [comment]
Happy for hearing that :))

**Comment by alexandreroutier** [comment]
Hi @Kobalt93,

I had the same issue than Noëlie and I was wondering if https://github.com/MIC-DKFZ/batchgenerators/issues/122 would solve this issue?

Best,
Alex
